### ISSUE TITLE
Example.json is missing

### ISSUE THREAD

**Issue by hargup** [reworkd/bananalyzer#59]
<img width="1321" alt="Screenshot 2024-02-07 at 1 36 17 PM" src="https://github.com/reworkd/bananalyzer/assets/2477788/24fa5d24-9475-4e72-b271-9077d8cee100">

The `example.json` file mentioned in the README is missing.

**Comment by awtkns** [comment]
Sorry about that, i think the folder got moved.

Here it is:
https://github.com/reworkd/bananalyzer/blob/main/static/examples.json

The evals can also be found here
https://github.com/reworkd/bananalyzer/blob/main/static

@hargup is this something you'd like to pr :)

**Comment by navjots18** [comment]
Hey, picking this one up, seems quite simple

**Comment by navjots18** [comment]
opened a [PR](https://github.com/reworkd/bananalyzer/pull/126) for this issue

**Comment by asim-shrestha** [comment]
Thanks @navjots18 !
